apiVersion: 1
contactPoints:
  - orgId: 1
    name: email-only
    receivers:
      - uid: ripent-email
        type: email
        settings:
          addresses: ${GRAFANA_ALERT_EMAILS}
        disableResolveMessage: false
policies:
  - orgId: 1
    receiver: email-only
    group_by: [alertname, service]
